{
  "formatVersion": "1.1",
  "component": {
    "group": "ren.nearby",
    "module": "autoPublish",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "fnjfeytadnc4veblqrbudwrybu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "autoPublish-0.0.1.jar",
          "url": "autoPublish-0.0.1.jar",
          "size": 37127,
          "sha512": "83f12c0037988ff967658e506f9078fb0dbbfe2a32cfa89f64c4ca3c0fb06d2c899a4d948f1f45bdd86482ca47ff5031fdd40ae3c4e3ff0c24f6028f590ccc4e",
          "sha256": "bb41f3a36e44a0a08d9ef57b87254274bc34336d0f1a5cc2d1fe17b8d8f04b98",
          "sha1": "a76eb1e14cf1fbdef2b3ffe20303eff54a9e9ad0",
          "md5": "42ea3aa016b08761b107ce32c316e9c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "autoPublish-0.0.1.jar",
          "url": "autoPublish-0.0.1.jar",
          "size": 37127,
          "sha512": "83f12c0037988ff967658e506f9078fb0dbbfe2a32cfa89f64c4ca3c0fb06d2c899a4d948f1f45bdd86482ca47ff5031fdd40ae3c4e3ff0c24f6028f590ccc4e",
          "sha256": "bb41f3a36e44a0a08d9ef57b87254274bc34336d0f1a5cc2d1fe17b8d8f04b98",
          "sha1": "a76eb1e14cf1fbdef2b3ffe20303eff54a9e9ad0",
          "md5": "42ea3aa016b08761b107ce32c316e9c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "autoPublish-0.0.1-sources.jar",
          "url": "autoPublish-0.0.1-sources.jar",
          "size": 5184,
          "sha512": "c79912949aab89841dfa29ac9d4312f02f02db8cba0973d4b935ab8c64a0a8e7b1388553de63f6c5dac941631b79ff27feec8987688fe818d8319e65bf7b0d63",
          "sha256": "61b72806b51dc36208333857a2c950ba266620f81bb8e21eefff3c00dc744612",
          "sha1": "f09fae9edd90deb528bfbfb04459150f7a0a4511",
          "md5": "730a906c655f6032e91d78a850e0825e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "autoPublish-0.0.1-javadoc.jar",
          "url": "autoPublish-0.0.1-javadoc.jar",
          "size": 261,
          "sha512": "29c4033f0bc97e3c1e84f1d0c5b67b85e426ecb125e632c995a542f79411d44dd653277f75e221b4a9a4300a73dc2398d39a0bfde19d5b838aa49e6173f7ad12",
          "sha256": "082a6d3e5a3df7a6a400363afdb064343bbba6e60bc72212aa499d70e3aa75f9",
          "sha1": "7876475006c3f05b6c10ce3d7447649724ce244e",
          "md5": "90919f7eb23ea3e7327910c5985e112d"
        }
      ]
    }
  ]
}
